<?php include ROOT_PATH.'/web/includes/header.php';?>
<html>
<head>
  <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Ignasi Ortiz, Carlos Leichner, Gabriel Farrus" />
	<meta name="description" content="IT Academy - FullStack LAMP" />
    <title>PhP Developers</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    
    <nav class="flex justify-center space-x-4">
        
        
        <h1>INDEX</h1>
        
      </nav>

      <hijo  class="flex justify-center items-center bg-gray-300 text-center w-full">

        </form>
        


            <form action = "" method = "POST" class="flex justify-center ">
              <section class="flex justify-center items-center bg-gray-300 text-center w-full ">
                <div class="max-w-md w-full  bg-white rounded p-6 my-4 space-y-4 ">
              
                <span class=" block text-sm font-medium text-slate-700">Choose an Option:</span>
              

                
                <div class = "flex-col flex items-center justify-evenly ">
                  <button type= "submit" id = "addtask" name = "addtask" class="my-4 w-40 py-4 bg-gray-600 hover:bg-gray-400 rounded text-sm font-bold text-pink-600 border-pink-600 transition duration-200">
                  <a href="addtask" class =" text-white underline hover:no-underline no-underline text-white-600 border-pink-600 transition duration-200 hover:text-white-600" >Create Task</a>

                  </button>
                  <button type= "submit" id = "addtask" name = "addtask" class="my-4  w-40 py-4 bg-gray-600 hover:bg-gray-400 rounded text-sm font-bold text-white-50 transition duration-200">
                  <a href="searchtask" class ="text-white underline hover:no-underline no-underline text-white-600 border-pink-600 transition duration-200 hover:text-white-600" >Search Task</a>

                  </button>
                  <button type= "submit" id = "addtask" name = "addtask" class="my-4 w-40 py-4 bg-gray-600 hover:bg-gray-400 rounded text-sm font-bold text-white-50 transition duration-200">
                  <a href="viewalltask" class ="text-white underline hover:no-underline no-underline text-white-600 border-pink-600 transition duration-200 hover:text-white-600" >View All Task</a>

                  </button>
                  <button type = "submit" id= "cancel" name ="cancel" class="my-4  w-40 py-4 bg-gray-600 hover:bg-gray-400 rounded text-sm font-bold text-white-600 border-pink-600 transition duration-200">
                  <a href="searchtodeletetask" class ="text-white underline hover:no-underline no-underline text-white-600 border-pink-600 transition duration-200 hover:text-white-600" >Delete Task</a>
                  </button>
                  </div> 
                </div>
              
              
          </div>
          </section>
        
        
      
        
        
    </form>

        
  </hijo>

    
  <?php
include ROOT_PATH.'/web/includes/footer.php';?>

</body>

        