<?php include ROOT_PATH.'/web/includes/header.php';
?>
<head>
  <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Ignasi Ortiz, Carlos Leichner, Gabriel Farrus" />
	<meta name="description" content="IT Academy - FullStack LAMP" />
    <title>PhP Developers</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
    <form id="frmLogin" action="index" method="post">
        <section class="flex justify-center items-center h-4/5 bg-gray-300">
            <div class="max-w-md w-full bg-white rounded p-6 my-44 space-y-4">
                <div class="mb-4">
                    <p class="text-gray-600">Benvingut a la:</p>
                    <h2 class="text-xl text-pink-600 font-bold">IT-ACADEMY Developers Team</h2>
                </div>
                <div>
                    <input type ="text" 
                            id   ="inpName"
                            name ="inpName" 
                            placeholder="Name"
                            class="w-full p-4 text-sm bg-gray-50 focus:outline-none focus:bg-yellow-100 border-2 border-gray-400 rounded text-gray-600">
                </div>
                <div>
                    <input type ="password" 
                            id   ="inpPwd"
                            name ="inpPwd"
                            placeholder="Password"
                            class="w-full p-4 text-sm bg-gray-50 focus:outline-none focus:bg-yellow-100 border-2 border-gray-400 rounded text-gray-600">
                </div>
                <div>
                    <button type ="submit"  
                            id   ="btnLogin" 
                            name ="btnLogin"
                            value="Accedeix"
                            form ="frmLogin" 
                            class="w-full py-4 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 transition duration-200">Accedeix
                    </button>
                </div>

                <div class="flex items-center justify-between">
                    <div class="flex flex-row items-center">
                        <input type="checkbox" class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                        <label for="comments" class="ml-2 text-sm font-normal text-gray-600">Recorda'm</label>
                    </div>
                <div>
                    <?php 
                        if (isset($_POST['inpName'])){
                            echo '<a class="text-sm text-red-600 hover:underline" href="adduser">Usuari no trobat. Vols registrar-te?</a>';
                        }
                    ?>                    
                </div>
            </div>
        </section>
    </form>      
    <?php
include ROOT_PATH.'/web/includes/footer.php';?>